# Now You Code In Class: Tricks of The Pandas Masters

We will try something a bit different in the Activity - A series of Pandas coding challenges!


For this Now You Code, you will need the Zomato api https://developers.zomato.com/api which provides API access to local area restaurants information.

In [54]:
import pandas as pd
import import_ipynb
import googleapi as google
import requests

pd.set_option('display.max_colwidth', None)
google_api_key = '751838d6b9978955679461c80a7df60bde4f093d'

## Warm-Up 1

Load the following data set into a data frame, called `exam_df`

https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv

HINT: observe the file format!

In [13]:
exam_df = pd.read_csv('https://raw.githubusercontent.com/mafudge/datasets/master/exam-scores/exam-scores.csv')
exam_df.sample(10)

,Class_Section,Exam_Version,Completion_Time,Made_Own_Study_Guide,Did_Exam_Prep Assignment,Studied_In_Groups,Student_Score,Percentage,Letter_Grade
57,M02,D,20,Y,Y,N,21,70.00%,C+
23,M01,D,35,?,?,?,13,43.30%,F
12,M01,B,35,Y,N,Y,29,96.70%,A
34,M02,A,45,Y,Y,N,24,80.00%,B
20,M01,C,60,?,?,?,22,73.30%,C+
36,M02,A,55,Y,Y,N,25,83.30%,B
8,M01,B,20,N,N,Y,13,43.30%,F
9,M01,B,20,Y,Y,N,27,90.00%,A-
2,M01,A,30,Y,Y,Y,30,100.00%,A
17,M01,C,45,N,Y,Y,23,76.70%,B-

## Warm-Up 2

Load the following HTML table into a data frame called `res_df`

https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition

HINT: Which table is it on the page?

In [20]:
vdf =  pd.read_html('https://en.wikipedia.org/wiki/Graphics_display_resolution#High-definition')
resolutions = vdf[5]
resolutions

      Name  H (px)  V (px)   H:V  H Ã— V (Mpx)
0      nHD     640     360  16:9        0.230
1      qHD     960     540  16:9        0.518
2       HD    1280     720  16:9        0.922
3      HD+    1600     900  16:9        1.440
4      FHD    1920    1080  16:9        2.074
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

## Warm-Up 3

For your `exam_df` display exams where the students made their own study guide  and finished in 30 minutes or less.

HINT: This can be multiple steps

In [36]:
madeown_df = exam_df[ exam_df['Made_Own_Study_Guide'] == 'Y']
made_fin_df = madeown_df [ madeown_df['Completion_Time'] < 30]

austin_df = made_fin_df['Exam_Version'] 
austin_df

mike_df = made_fin_df[   {'Exam_Version', "Letter_Grade"}   ]
mike_df

   Exam_Version Letter_Grade
7             B           B+
9             B           A-
14            C           B+
48            C           A-
57            D           C+

In [37]:
made_fin_df.columns

Index(['Class_Section', 'Exam_Version', 'Completion_Time',
       'Made_Own_Study_Guide', 'Did_Exam_Prep Assignment', 'Studied_In_Groups',
       'Student_Score', 'Percentage', 'Letter_Grade'],
      dtype='object')

In [24]:
final_df = exam_df[  exam_df['Made_Own_Study_Guide'] == 'Y'][ exam_df['Completion_Time']< 30 ]
final_df

<ipython-input-24-857ee2aafb05>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  final_df = exam_df[  exam_df['Made_Own_Study_Guide'] == 'Y'][ exam_df['Completion_Time']< 30 ]

,Class_Section,Exam_Version,Completion_Time,Made_Own_Study_Guide,Did_Exam_Prep Assignment,Studied_In_Groups,Student_Score,Percentage,Letter_Grade
7,M01,B,15,Y,Y,Y,26,86.70%,B+
9,M01,B,20,Y,Y,N,27,90.00%,A-
14,M01,C,20,Y,Y,Y,26,86.70%,B+
48,M02,C,25,Y,Y,Y,28,93.30%,A-
57,M02,D,20,Y,Y,N,21,70.00%,C+

## Warm-Up 4

For your `res_df`, display the displays which are larger than 1920 x 1080. Show columns `Name` and `H:V` only

HINT: Again, think multiple steps

In [40]:
res_h = resolutions [ resolutions['H (px)'] >1920]
res_hv = res_h [ res_h['V (px)'] >1080]
res_hv

      Name  H (px)  V (px)   H:V  H Ã— V (Mpx)
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

In [42]:
resolutions[5:]

      Name  H (px)  V (px)   H:V  H Ã— V (Mpx)
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

In [50]:
resolutions[ (resolutions['H (px)'] > 1920) & (resolutions['V (px)'] > 1080) ]

      Name  H (px)  V (px)   H:V  H Ã— V (Mpx)
5   (W)QHD    2560    1440  16:9        3.686
6     QHD+    3200    1800  16:9        5.760
7   4K UHD    3840    2160  16:9        8.294
8       5K    5120    2880  16:9       14.746
9   8K UHD    7680    4320  16:9       33.178
10     16K   15360    8640  16:9      132.710

## Challenge 1

1. Search the Open Street Maps  geocode api for "Syracuse" (leave off the NY) put the results in a dataframe (there should be several results). 

Example:
https://nominatim.openstreetmap.org/search?q=Syracuse&format=json

In [51]:
url = 'https://nominatim.openstreetmap.org/search?q=Syracuse&format=json'
response = requests.get(url)
response.raise_for_status()
locations = response.json()
locations

[{'place_id': 257841956,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 174916,
  'boundingbox': ['42.9843709', '43.086102', '-76.2046029', '-76.074084'],
  'lat': '43.0481221',
  'lon': '-76.1474244',
  'display_name': 'Syracuse, Onondaga County, New York, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.6867762857760726,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 257728182,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 39169,
  'boundingbox': ['36.9477054', '37.1156703', '15.0829726', '15.3367251'],
  'lat': '37.0646139',
  'lon': '15.2907196',
  'display_name': 'Siracusa, Sicilia, Italia',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.5980544326919952,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 257785961,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 129906,
  'boundingbox': ['37.941272', '37.990492', '-101.816776', '-101.736708'],
  'lat': '37.9805686',
  'lon': '-101.7526719',
  'display_name': 'Syracuse, Hamilton County, Kansas, 67878, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.5354945081461472,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 257190791,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 169314,
  'boundingbox': ['40.651206', '40.672865', '-96.197821', '-96.172004'],
  'lat': '40.657224',
  'lon': '-96.186398',
  'display_name': 'Syracuse, Otoe County, Nebraska, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.46112554102268,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 258183983,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 198737,
  'boundingbox': ['41.0529648', '41.11093', '-112.1159667', '-112.035662'],
  'lat': '41.0895938',
  'lon': '-112.0638903',
  'display_name': 'Syracuse, Davis County, Utah, 84075, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.436855406087553,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 69010415,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'node',
  'osm_id': 6241108067,
  'boundingbox': ['43.0718312', '43.0818312', '-76.1744003', '-76.1644003'],
  'lat': '43.0768312',
  'lon': '-76.1694003',
  'display_name': 'Syracuse, 131, NBT Bank Parkway, Syracuse, Onondaga County, New York, 13208, United States',
  'class': 'railway',
  'type': 'station',
  'importance': 0.4272524353626238,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//transport_train_station2.p.20.png'},
 {'place_id': 257152602,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 141314,
  'boundingbox': ['38.665793', '38.67337', '-92.883419', '-92.869404'],
  'lat': '38.6700209',
  'lon': '-92.8732509',
  'display_name': 'Syracuse, Morgan County, Missouri, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.42043947441223084,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 257782630,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 127610,
  'boundingbox': ['41.403028', '41.43607', '-85.768612', '-85.734116'],
  'lat': '41.4278409',
  'lon': '-85.7524957',
  'display_name': 'Syracuse, Kosciusko County, Indiana, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.42043947441223084,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 258361658,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 182667,
  'boundingbox': ['38.9922728', '39.007177', '-81.9841277', '-81.943146'],
  'lat': '38.9975789',
  'lon': '-81.9740274',
  'display_name': 'Syracuse, Meigs County, Ohio, 45779, United States',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.4090422669932742,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'},
 {'place_id': 257738503,
  'licence': 'Data Â© OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 39155,
  'boundingbox': ['36.6441671', '37.4128826', '14.7729261', '15.3367251'],
  'lat': '37.02983715',
  'lon': '15.086780069913484',
  'display_name': 'Siracusa, Sicilia, Italia',
  'class': 'boundary',
  'type': 'administrative',
  'importance': 0.4042848260470168,
  'icon': 'https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png'}]

## Challenge 2

1. Load the locations into a dataframe. using the `pd.DataFrame()` method. Start with whatever is of type `list` as that will automatically place it into a `DataFrame`

In [55]:
locations_df = pd.DataFrame(locations)
locations_df[ { 'display_name', 'lat', 'lon'}]

,display_name,lon,lat
0,"Syracuse, Onondaga County, New York, United States",-76.1474244,43.0481221
1,"Siracusa, Sicilia, Italia",15.2907196,37.0646139
2,"Syracuse, Hamilton County, Kansas, 67878, United States",-101.7526719,37.9805686
3,"Syracuse, Otoe County, Nebraska, United States",-96.186398,40.657224
4,"Syracuse, Davis County, Utah, 84075, United States",-112.0638903,41.0895938
5,"Syracuse, 131, NBT Bank Parkway, Syracuse, Onondaga County, New York, 13208, United States",-76.1694003,43.0768312
6,"Syracuse, Morgan County, Missouri, United States",-92.8732509,38.6700209
7,"Syracuse, Kosciusko County, Indiana, United States",-85.7524957,41.4278409
8,"Syracuse, Meigs County, Ohio, 45779, United States",-81.9740274,38.9975789
9,"Siracusa, Sicilia, Italia",15.086780069913484,37.02983715

## Challenge 3

1. Let's call the IST256 google places search api, looking for bars in the Syracuse NY area, and load the results into a dataframe. You can call `google.googlePlacesSearch()` With these inputs lat=`43.0481`, lng=`-76.1474`, type=`'bar'`

In [60]:
places = google.googlePlacesSearch(google_api_key, '43.0481','-76.1474', 'bar')
places_df = pd.DataFrame(places)
places_df

,business_status,geometry,icon,name,opening_hours,photos,place_id,plus_code,price_level,rating,reference,scope,types,user_ratings_total,vicinity,permanently_closed
0,OPERATIONAL,"{'location': {'lat': 43.0485021, 'lng': -76.15575319999999}, 'viewport': {'northeast': {'lat': 43.0499588802915, 'lng': -76.15439441970848}, 'southwest': {'lat': 43.04726091970851, 'lng': -76.15709238029149}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Kitty Hoyne's Irish Pub,{'open_now': True},"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/112556789907904985640"">Jasmine Hindman</a>'], 'photo_reference': 'ATtYBwJdhyXmpgdUo6Y9GT2rBRm2IAXiL-E6D2yR6hDgw2itoqdrBh8JBcKnlmsJMjEqMQh8GyMCBRwO9gXy8Pm6egT6hE9laHmto2pCU0h6bbss-fGcN65pZEZw9y7PgeWgs2f4XFhl5dU5hrMZl6UP_JPktiXVfjKsf5xokEreo25LCftP', 'width': 4032}]",ChIJ2abhW8fz2YkRq_i-OkgGh7c,"{'compound_code': '2RXV+CM Syracuse, NY, USA', 'global_code': '87M52RXV+CM'}",2.0,4.6,ChIJ2abhW8fz2YkRq_i-OkgGh7c,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",1246,"301 West Fayette Street, Syracuse",NaN
1,OPERATIONAL,"{'location': {'lat': 43.04672, 'lng': -76.13756699999999}, 'viewport': {'northeast': {'lat': 43.0480367302915, 'lng': -76.1363070697085}, 'southwest': {'lat': 43.0453387697085, 'lng': -76.13900503029151}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Phoebe's Restaurant & Coffee Lounge,{'open_now': False},"[{'height': 4032, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/116794142480052692210"">Phoebe&#39;s Restaurant &amp; Coffee Lounge</a>'], 'photo_reference': 'ATtYBwKty3TDH50weBYHsXZlYmVBE2Pi6Nm2mskekLKt2yVYtUg2rymXxLK0Wnp46WRGvysUJkQf1PvXPCMyP-ctoJuhLscFmTP7_BD-GQLMS1jHNMVhwKGObZRCZn6fPdWw7XzpEGRrpH7PMeqpvuGaTPYhikx4PdZ8gpCJJFxhzg7mHEs0', 'width': 3024}]",ChIJ4XPPn6bz2YkRKrZtWuXTaA0,"{'compound_code': '2VW6+MX Syracuse, NY, USA', 'global_code': '87M52VW6+MX'}",2.0,4.6,ChIJ4XPPn6bz2YkRKrZtWuXTaA0,GOOGLE,"[meal_takeaway, cafe, bar, restaurant, food, point_of_interest, store, establishment]",485,"900 East Genesee Street, Syracuse",NaN
2,OPERATIONAL,"{'location': {'lat': 43.0478305, 'lng': -76.15470959999999}, 'viewport': {'northeast': {'lat': 43.04917948029149, 'lng': -76.15336061970848}, 'southwest': {'lat': 43.0464815197085, 'lng': -76.1560585802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Blue Tusk,{'open_now': True},"[{'height': 1366, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/115324265651211901087"">Blue Tusk</a>'], 'photo_reference': 'ATtYBwKvMcUkBJ-rEfmH3X1O7ct9vIK0GZ5EYCVR4yBcC0F-7N6lrw2Bfg7nCbbD_biXHT7Wgpj7tNPi7-ARa0QTOif05N3Vdv-lewvorbPbgSzG0wFR5l5t7tAnTecBdRhcR2QwjvTRC53WmOrOzARexSE_xW65hT498byR7wt79-mnFYOB', 'width': 2048}]",ChIJYcGiq7jz2YkR2Ah1e3mkNOg,"{'compound_code': '2RXW+44 Syracuse, NY, USA', 'global_code': '87M52RXW+44'}",2.0,4.4,ChIJYcGiq7jz2YkR2Ah1e3mkNOg,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",707,"165 Walton Street, Syracuse",NaN
3,OPERATIONAL,"{'location': {'lat': 43.0418639, 'lng': -76.13684169999999}, 'viewport': {'northeast': {'lat': 43.04321178029149, 'lng': -76.13539986970851}, 'southwest': {'lat': 43.04051381970849, 'lng': -76.13809783029151}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Faegan's Cafe & Pub,{'open_now': False},"[{'height': 1210, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108084176728678728835"">Faegan&#39;s Cafe &amp; Pub</a>'], 'photo_reference': 'ATtYBwL7FWHupaeu_EZ0VagbFZ7FMXX_dYUoNUHL9Jqmm7udA0OrRpvEiGyZMtXqVssM6NhOGOIPN6rqz2PausS3ZatuE2Bswe0sZOqEVkTws4TF5iW1ycTLNAuFXXl2aML9SRpH22Zf6lK09N5t--iT6le4hcvXZQWGLzH9QtiDIwrXPKkw', 'width': 2600}]",ChIJn5r_W5_z2YkR67VB2u5qyRw,"{'compound_code': '2VR7+P7 Syracuse, NY, USA', 'global_code': '87M52VR7+P7'}",2.0,4.3,ChIJn5r_W5_z2YkR67VB2u5qyRw,GOOGLE,"[cafe, bar, restaurant, food, point_of_interest, establishment]",428,"734 South Crouse Avenue, Syracuse",NaN
4,CLOSED_TEMPORARILY,"{'location': {'lat': 43.0481128, 'lng': -76.15388759999999}, 'viewport': {'northeast': {'lat': 43.04947563029149, 'lng': -76.15238011970848}, 'southwest': {'lat': 43.0467776697085, 'lng': -76.1550780802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Syracuse Suds Factory,NaN,"[{'height': 2666, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100850734738657404193"">Solas Studios Photography</a>'], 'photo_reference': 'ATtYBwJQxQ1udkNZkX6KsCVBZkAV-U3PXsnAtPx_m4mUy90kMaSjVa5Bm273lLBzB5IyEql31rDfd8D7be5aL5U1ohXCT2_JsKRj7PQ8mebI_bbwPa0fz-WoP7XWb67Fs-MwmQK83A5RgYc5sk3PGnw5LF6amb62MOG20cK1NQoysHCsDJVD', 'width': 4000}]",ChIJ42EzyLjz2YkRz4aKaDCeDbw,"{'compound_code': '2RXW+6C Syracuse, NY, USA', 'global_code': '87M52RXW+6C'}",2.0,3.3,ChIJ42EzyLjz2YkRz4aKaDCeDbw,GOOGLE,"[bar, point_of_interest, establishment]",140,"320 South Clinton Street, Syracuse",True
5,OPERATIONAL,"{'location': {'lat': 43.05074, 'lng': -76.154507}, 'viewport': {'northeast': {'lat': 43.0520889802915, 'lng': -76.15315801970848}, 'southwest': {'lat': 43.0493910197085, 'lng': -76.15585598029149}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Saltine Warrior Sports Pub,{'open_now': True},"[{'height': 1000, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108754994177934343905"">Saltine Warrior Sports Pub</a>'], 'photo_reference': 'ATtYBwJFmS51jaikXggLhaCiNRVUarWeeIjjLATrGpXKEVBEQwX13-LqpfcsUl-4LQoqRiOnWxfvymrU05L1i-G9o-oXAIm3OoRXLFLvR-CXxGPTtIEbzxAnDqwYfHWG-PtoP1o1yUggxxuB2B1Hnj85OzTqa7x0bsjT0vrv_HO1RUZ8R31g', 'width': 1500}]",ChIJ4eXBZ7jz2YkRWwzq6jh85dM,"{'compound_code': '3R2W+75 Syracuse, NY, USA', 'global_code': '87M53R2W+75'}",2.0,4.0,ChIJ4eXBZ7jz2YkRWwzq6jh85dM,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",119,"214 West Water Street, Syracuse",NaN
6,OPERATIONAL,"{'location': {'lat': 43.048176, 'lng': -76.153368}, 'viewport': {'northeast': {'lat': 43.0495457802915, 'lng': -76.1521210697085}, 'southwest': {'lat': 43.0468478197085, 'lng': -76.1548190302915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Al's Wine & Whiskey Lounge,{'open_now': True},"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100361962513131275677"">Reine H</a>'], 'photo_reference': 'ATtYBwIj59e0ll3aS8lnqoA9Cp7PXAADE_28snh3toFrZE7DSkBPjlFNT_sth5G5EF4EoTvzhCLvHMOIMQn4BtXP-6cuEg_qZw0cRg2Vt5VMbOCYl32T3wShxK5S9dmnp2ZZnoH7YSm8wCC31nuIpBTo3bsCK39UdEwthx2t__N1FFrJGDM', 'width': 4032}]",ChIJVfyEyLjz2YkRf7FRJXkhgd0,"{'compound_code': '2RXW+7M Syracuse, NY, USA', 'global_code': '87M52RXW+7M'}",2.0,4.6,ChIJVfyEyLjz2YkRf7FRJXkhgd0,GOOGLE,"[bar, point_of_interest, establishment]",699,"321 South Clinton Street, Syracuse",NaN
7,OPERATIONAL,"{'location': {'lat': 43.052942, 'lng': -76.1537547}, 'viewport': {'northeast': {'lat': 43.0543317302915, 'lng': -76.1525218197085}, 'southwest': {'lat': 43.0516337697085, 'lng': -76.1552197802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Trexx,{'open_now': False},"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/114968416506485689423"">Theressa Bienvenue</a>'], 'photo_reference': 'ATtYBwJ_jqO8Tv6-oC9kVz5_bbNZt1oIpx1oBk3M4i9NGE9-FTI8p4WtAl0s4-6m0qkLgxAiwj3Xh98E0dMPOFQn1Iu-pebxg7-44z9Fz1M02leKJnunecOLxSc3pPuN2lBjZsjBRhkiHS6SXYZG1ITOYG3UD3wtLUnDXxbuXQWY6ITTx_IZ', 'width': 4032}]",ChIJnRi-jbfz2YkRBpeSSVhhMxE,"{'compound_code': '3R3W+5F Syracuse, NY, USA', 'global_code': '87M53R3W+5F'}",1.0,4.1,ChIJnRi-jbfz2YkRBpeSSVhhMxE,GOOGLE,"[night_club, bar, restaurant, food, point_of_interest, establishment]",66,"323 North Clinton Street, Syracuse",NaN
8,OPERATIONAL,"{'location': {'lat': 43.05237700000001, 'lng': -76.138954}, 'viewport': {'northeast': {'lat': 43.0536381302915, 'lng': -76.1376070197085}, 'southwest': {'lat': 43.0509401697085, 'lng': -76.1403049802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Guilfoil's Irish Pub,{'open_now': True},"[{'height': 452, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/101335463993932786042"">Guilfoil&#39;s Irish Pub</a>'], 'photo_reference': 'ATtYBwKtGwcfQ3tH_75DpxA0py90NKtPzm2SL3uYVv2wTk2LMMFVxg5qm9n2uRyqfGAFwUZ5iggJgrzXM2F7sVQkGSTdtSwOQBYC_PJggZr7iDKHs2p0pD-vqHzhzR8dxPfYlbsc2ibZoTsYVZ6AwkYBxdsYhh9cwgWrywOdEuS_Fj57eeSy', 'width': 804}]",ChIJDfWlPa_z2YkRHNJzLnjnILM,"{'compound_code': '3V26+XC Syracuse, NY, USA', 'global_code': '87M53V26+XC'}",1.0,4.6,ChIJDfWlPa_z2YkRHNJzLnjnILM,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",144,"501 Burnet Avenue, Syracuse",NaN
9,OPERATIONAL,"{'location': {'lat': 43.0481533, 'lng': -76.15441729999999}, 'viewport': {'northeast': {'lat': 43.04940938029149, 'lng': -76.15308206970849}, 'southwest': {'lat': 43.04671141970849, 'lng': -76.1557800302915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,The Hops Spot,{'open_now': True},"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100236607195278254777"">Andrew Schutt</a>'], 'photo_reference': 'ATtYBwJtcEUCMz8fgp4W1eqbLDUs7tmIQY0GPIwUG6vOuiqMW89lmZLWTIXfo_wwF8kqjXE7vSDb60DmzXMvvHSvsalJIj0shuMnSV9frZZB9HYxCsSyPUTmUmTIqPv6vTwch1U5BcbxUHDsNIcQdjGFpttAhabGbTLwXjjztk5uMmndM4kJ', 'width': 4032}]",ChIJvfSLcA0T2IkRfWBTZpwlidY,"{'compound_code': '2RXW+76 Syracuse, NY, USA', 'global_code': '87M52RXW+76'}",2.0,4.4,ChIJvfSLcA0T2IkRfWBTZpwlidY,GOOGLE,"[bar, liquor_store, restaurant, food, point_of_interest, store, establishment]",444,"116 Walton Street, Syracuse",NaN
10,OPERATIONAL,"{'location': {'lat': 43.05012019999999, 'lng': -76.1515045}, 'viewport': {'northeast': {'lat': 43.05157973029149, 'lng': -76.15007181970849}, 'southwest': {'lat': 43.0488817697085, 'lng': -76.15276978029151}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Maxwells,{'open_now': True},"[{'height': 1960, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108530648779026001981"">Maxwells</a>'], 'photo_reference': 'ATtYBwLALY9zCvPP70QAFnL28KPJ_uA3OCjzHPzV44RC-Fp_BBJMd6fmKERcOVlLA_UCzaNWHNT6iaAM0fi5ykO1iFMvH46Uh_8hKAhkjtVfxI0GCLwQJj4r08CvZb_5VUyMb1qYBpcEbgNXxruN2CJoT1HhMdbXiuZNvp9PIj4HKcJFzRYF', 'width': 1960}]",ChIJM86Fpbnz2YkRKrGFqtQqBi8,"{'compound_code': '3R2X+29 Syracuse, NY, USA', 'global_code': '87M53R2X+29'}",2.0,4.3,ChIJM86Fpbnz2YkRKrGFqtQqBi8,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",279,"122 East Genesee Street, Syracuse",NaN
11,OPERATIONAL,"{'location': {'lat': 43.04941199999999, 'lng': -76.1520069}, 'viewport': {'northeast': {'lat': 43.0507728802915, 'lng': -76.1507617197085}, 'southwest': {'lat': 43.0480749197085, 'lng': -76.1534596802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Anything But Beer,{'open_now': False},"[{'height': 922, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/104981910177197126804"">Anything But Beer</a>'], 'photo_reference': 'ATtYBwIHd9ctpCeRKjeo8FP4z95lyYO3U7avwxS3Xr9htx87Jvy8ZBWs1EmLLFvvZ1sLl3TEuH9Yt43XPxBTVcCMJcLeCRibFqE6saXlXrQsOmYDtee1kjYxNoh-4DBjGOsB1pF8ADHZvVhzvep5SwhNZDiN9lRORPS27jDB-8Z0qmy98PYM', 'width': 918}]",ChIJgRICEd7z2YkREtShfi5Pgzo,"{'compound_code': '2RXX+Q5 Syracuse, NY, USA', 'global_code': '87M52RXX+Q5'}",NaN,4.5,ChIJgRICEd7z2YkREtShfi5Pgzo,GOOGLE,"[restaurant, meal_delivery, bar, food, point_of_interest, establishment]",70,"201 South Salina Street, Syracuse",NaN
12,OPERATIONAL,"{'location': {'lat': 43.05069699999999, 'lng': -76.15127199999999}, 'viewport': {'northeast': {'lat': 43.0521434302915, 'lng': -76.14991181970848}, 'southwest': {'lat': 43.0494454697085, 'lng': -76.1526097802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,The Evergreen,{'open_now': True},"[{'height': 1169, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/105467604264551483338"">The Evergreen</a>'], 'photo_reference': 'ATtYBwLMHL206ak_o6HUm1niDktCC1RDsjgRfbRKnju0rOywQZdT2KsiYmsplpWrsTxXpq9ZHkVndQNhb0BpId2IfOZ1cDRtTFED_vvP4Ptaj51-GErY8mRhtuZ5lI5CxkF1zeSKvHI9lOJI2bAon0hsqLV-APSL_bsiLkac_tlwYcRgoM5b', 'width': 1920}]",ChIJHegrubnz2YkRoEpk_R7BDTg,"{'compound_code': '3R2X+7F Syracuse, NY, USA', 'global_code': '87M53R2X+7F'}",2.0,4.5,ChIJHegrubnz2YkRoEpk_R7BDTg,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",552,"125 East Water Street, Syracuse",NaN
13,OPERATIONAL,"{'location': {'lat': 43.0476609, 'lng': -76.14187679999999}, 'viewport': {'northeast': {'lat': 43.0490852802915, 'lng': -76.1406638197085}, 'southwest': {'lat': 43.0463873197085, 'lng': -76.1433617802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Weighlock Lounge,{'open_now': False},"[{'height': 1920, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100030972936603522177"">Cat Lang</a>'], 'photo_reference': 'ATtYBwI2KNcNTUcrY1k4V0SjoblRrbguRHPAWzPOsRdR0tUiBnGBSGLsXU8CQuLxd8z7KQ5hO4FuS9DOE84-0Y23sNX4xNuE-bKVnnk1iXQ623kvT2_wuj5EYiaSh9ngHErMp62EPWLUWfXi5K2xSdDWsGd-9hQcqpNaKk21Rb4Msg2xtUk7', 'width': 1080}]",ChIJ2SNg6aTz2YkRa1B-BaUA2rA,"{'compound_code': '2VX5+36 Syracuse, NY, USA', 'global_code': '87M52VX5+36'}",NaN,4.8,ChIJ2SNg6aTz2YkRa1B-BaUA2rA,GOOGLE,"[bar, point_of_interest, establishment]",4,"701 East Genesee Street suite b, Syracuse",NaN
14,OPERATIONAL,"{'location': {'lat': 43.048347, 'lng': -76.15326999999999}, 'viewport': {'northeast': {'lat': 43.0497036302915, 'lng': -76.15207351970848}, 'southwest': {'lat': 43.0470056697085, 'lng': -76.1547714802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Funk 'n Waffles,{'open_now': False},"[{'height': 381, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/113254511588149162028"">Funk &#39;n Waffles</a>'], 'photo_reference': 'ATtYBwLslllgY8-8yVQtqvOTKMLZJ7v1pHIQpS6ywYmA0WVgdQsh2LNwfihlN8r5yD1GB7C-8uPtKpyGTtSkiY_gEjjLIcjVDirLovYEIoDT5_s7Bqjhn2NZirSoLdQ1gbJ_3ErCva4negFgDfpBpfN0lGcS3c-T76tP0EEzeyz7UhfO_Ncn', 'width': 620}]",ChIJLX-Pxrjz2YkRLe-7F_VN3HE,"{'compound_code': '2RXW+8M Syracuse, NY, USA', 'global_code': '87M52RXW+8M'}",NaN,4.4,ChIJLX-Pxrjz2YkRLe-7F_VN3HE,GOOGLE,"[cafe, bar, restaurant, food, point_of_interest, establishment]",1736,"307-13 South Clinton Street, Syracuse",NaN
15,OPERATIONAL,"{'location': {'lat': 43.0444715, 'lng': -76.151072}, 'viewport': {'northeast': {'lat': 43.0457510302915, 'lng': -76.14978051970849}, 'southwest': {'lat': 43.0430530697085, 'lng': -76.1524784802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Shaughnessy's Irish Pub,{'open_now': True},"[{'height': 4016, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/113943995077151847284"">Shaughnessy&#39;s Irish Pub</a>'], 'photo_reference': 'ATtYBwKbFXD6-eEWh1Sstd7qMGCGeE3ZZREzIqKqVn5g9aaOVR1XMSiG0xyST9d7-4jXJNVOWeAS39F-p8N6YE2TRpe33GIG0VyLDokkUKqx0YNth_rkc4luwZDcfbBdHtqwHM-oXRzH1MwfDX7itz9xSsmONUrVebXrNdTsWIOJRUMchIe6', 'width': 6016}]",ChIJo8R5WL7z2YkRRcysmcsM3yo,"{'compound_code': '2RVX+QH Syracuse, NY, USA', 'global_code': '87M52RVX+QH'}",2.0,4.1,ChIJo8R5WL7z2YkRRcysmcsM3yo,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",530,"550 South Warren Street, Syracuse",NaN
16,OPERATIONAL,"{'location': {'lat': 43.0485311, 'lng': -76.15506429999999}, 'viewport': {'northeast': {'lat': 43.0499700302915, 'lng': -76.1537140697085}, 'southwest': {'lat': 43.0472720697085, 'lng': -76.1564120302915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,The York,{'open_now': False},"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/106614825764704404196"">DeLancey Miller</a>'], 'photo_reference': 'ATtYBwJ5u7uXOKYxuVlbq3-2LocSA-HyzzPNg2vO-FXcWPfjyxbKvopVNmuzDNnz8h2POy0xC7QE1MpHKw4fz9fpOOEyfSEodVKAghTIUHxMbXMfbWSeXW4M9Q92ODoo-RN39W6ea3nvKaaP71TfD-Cc-Qbvjb44RKNicYlmnReN2-FruVzh', 'width': 3024}]",ChIJJdSLp7jz2YkRLDrtGu98O-M,"{'compound_code': '2RXV+CX Syracuse, NY, USA', 'global_code': '87M52RXV+CX'}",2.0,4.3,ChIJJdSLp7jz2YkRLDrtGu98O-M,GOOGLE,"[night_club, bar, restaurant, food, point_of_interest, establishment]",373,"247 West Fayette Street, Syracuse",NaN
17,OPERATIONAL,"{'location': {'lat': 43.0442185, 'lng': -76.1490625}, 'viewport': {'northeast': {'lat': 43.0456136802915, 'lng': -76.1477136197085}, 'southwest': {'lat': 43.0429157197085, 'lng': -76.1504115802915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Ale 'n' Angus Pub,{'open_now': False},"[{'height': 4032, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/102416727465053559547"">Ale &#39;n&#39; Angus Pub</a>'], 'photo_reference': 'ATtYBwK7iWaXqUYXGmwPfWNP8E1KbHbrxPi9aLg24L8mNzSWHs4pCLA-JaifAAcFqVuqKE6KMjv6iMrffh227sM6-azpaD9onwE8m3pJVPQduwmyC9Jo3BB4i5KB_xqEQnCVWhmIyKJ1D-oGJPJdV_0g4Npn8F82iOkEXU9BMgUQWgmVVOU', 'width': 3024}]",ChIJJa942r3z2YkREJnXnrSTZK0,"{'compound_code': '2VV2+M9 Syracuse, NY, USA', 'global_code': '87M52VV2+M9'}",2.0,4.5,ChIJJa942r3z2YkREJnXnrSTZK0,GOOGLE,"[bar, point_of_interest, establishment]",382,"238 Harrison Street, Syracuse",NaN
18,OPERATIONAL,"{'location': {'lat': 43.04758830000001, 'lng': -76.154541}, 'viewport': {'northeast': {'lat': 43.04885438029151, 'lng': -76.15314281970849}, 'southwest': {'lat': 43.04615641970851, 'lng': -76.15584078029151}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Bistro Elephant,NaN,"[{'height': 1365, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108937448623068417193"">Jim Hilker</a>'], 'photo_reference': 'ATtYBwLdwgSEj2Xwe1aTAHB_Muv22cogfOFKvhB8FzZgGGmPxoHkojedNrSHrlmt71KzdRJ92-0R0uVf4zar1w29uJnFzp5lyggr41IDldBSeMHjY3x-0rRrbuH_du5TGYpjtKIatllI580HeyVRWC84Tm6kMzLZIQuxVodHZgwHEkDVdo9p', 'width': 2048}]",ChIJL0sWVL_z2YkRQhZzBYHjmPs,"{'compound_code': '2RXW+25 Syracuse, NY, USA', 'global_code': '87M52RXW+25'}",NaN,4.4,ChIJL0sWVL_z2YkRQhZzBYHjmPs,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",34,"238 West Jefferson Street, Syracuse",NaN
19,OPERATIONAL,"{'location': {'lat': 43.04852869999999, 'lng': -76.1533906}, 'viewport': {'northeast': {'lat': 43.0498707802915, 'lng': -76.15213536970847}, 'southwest': {'lat': 43.0471728197085, 'lng': -76.1548333302915}}}",https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Clinton Street Pub,{'open_now': True},"[{'height': 4032, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/107276703630995618848"">Clinton Street Pub</a>'], 'photo_reference': 'ATtYBwJ7XSmToaOHY0O9O1LAJM8tIBTBkO5sJLGQTHmz0ndmGSUv3tx4pgnUaYNpHgv0f_MEbhPo09rCBk-IaOgLhhaCAsl_DtPkKMsUSe7aT5JBUWwEcr_aGZsxnvNSawoCvm6LI9p39eX1eQWyacou6JOKx2BTZ_Tfon6fRFnj1Xi3Ciyg', 'width': 3024}]",ChIJvwKdwbjz2YkR2pHlLXgBxek,"{'compound_code': '2RXW+CJ Syracuse, NY, USA', 'global_code': '87M52RXW+CJ'}",1.0,4.0,ChIJvwKdwbjz2YkR2pHlLXgBxek,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",403,"127 West Fayette Street, Syracuse",NaN

## Challenge 4

Notice the nested JSON. Yuk. This can be fixed using `pd.json_normalize` instead of `pd.DataFrame`.

Fix the results above so that the nested JSON is flattened in the dataframe.

In [61]:
places_df = pd.json_normalize(places)
places_df

,business_status,icon,name,photos,place_id,price_level,rating,reference,scope,types,...,geometry.location.lat,geometry.location.lng,geometry.viewport.northeast.lat,geometry.viewport.northeast.lng,geometry.viewport.southwest.lat,geometry.viewport.southwest.lng,opening_hours.open_now,plus_code.compound_code,plus_code.global_code,permanently_closed
0,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Kitty Hoyne's Irish Pub,"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/112556789907904985640"">Jasmine Hindman</a>'], 'photo_reference': 'ATtYBwJdhyXmpgdUo6Y9GT2rBRm2IAXiL-E6D2yR6hDgw2itoqdrBh8JBcKnlmsJMjEqMQh8GyMCBRwO9gXy8Pm6egT6hE9laHmto2pCU0h6bbss-fGcN65pZEZw9y7PgeWgs2f4XFhl5dU5hrMZl6UP_JPktiXVfjKsf5xokEreo25LCftP', 'width': 4032}]",ChIJ2abhW8fz2YkRq_i-OkgGh7c,2.0,4.6,ChIJ2abhW8fz2YkRq_i-OkgGh7c,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.048502,-76.155753,43.049959,-76.154394,43.047261,-76.157092,True,"2RXV+CM Syracuse, NY, USA",87M52RXV+CM,NaN
1,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Phoebe's Restaurant & Coffee Lounge,"[{'height': 4032, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/116794142480052692210"">Phoebe&#39;s Restaurant &amp; Coffee Lounge</a>'], 'photo_reference': 'ATtYBwKty3TDH50weBYHsXZlYmVBE2Pi6Nm2mskekLKt2yVYtUg2rymXxLK0Wnp46WRGvysUJkQf1PvXPCMyP-ctoJuhLscFmTP7_BD-GQLMS1jHNMVhwKGObZRCZn6fPdWw7XzpEGRrpH7PMeqpvuGaTPYhikx4PdZ8gpCJJFxhzg7mHEs0', 'width': 3024}]",ChIJ4XPPn6bz2YkRKrZtWuXTaA0,2.0,4.6,ChIJ4XPPn6bz2YkRKrZtWuXTaA0,GOOGLE,"[meal_takeaway, cafe, bar, restaurant, food, point_of_interest, store, establishment]",...,43.046720,-76.137567,43.048037,-76.136307,43.045339,-76.139005,False,"2VW6+MX Syracuse, NY, USA",87M52VW6+MX,NaN
2,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Blue Tusk,"[{'height': 1366, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/115324265651211901087"">Blue Tusk</a>'], 'photo_reference': 'ATtYBwKvMcUkBJ-rEfmH3X1O7ct9vIK0GZ5EYCVR4yBcC0F-7N6lrw2Bfg7nCbbD_biXHT7Wgpj7tNPi7-ARa0QTOif05N3Vdv-lewvorbPbgSzG0wFR5l5t7tAnTecBdRhcR2QwjvTRC53WmOrOzARexSE_xW65hT498byR7wt79-mnFYOB', 'width': 2048}]",ChIJYcGiq7jz2YkR2Ah1e3mkNOg,2.0,4.4,ChIJYcGiq7jz2YkR2Ah1e3mkNOg,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.047831,-76.154710,43.049179,-76.153361,43.046482,-76.156059,True,"2RXW+44 Syracuse, NY, USA",87M52RXW+44,NaN
3,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Faegan's Cafe & Pub,"[{'height': 1210, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108084176728678728835"">Faegan&#39;s Cafe &amp; Pub</a>'], 'photo_reference': 'ATtYBwL7FWHupaeu_EZ0VagbFZ7FMXX_dYUoNUHL9Jqmm7udA0OrRpvEiGyZMtXqVssM6NhOGOIPN6rqz2PausS3ZatuE2Bswe0sZOqEVkTws4TF5iW1ycTLNAuFXXl2aML9SRpH22Zf6lK09N5t--iT6le4hcvXZQWGLzH9QtiDIwrXPKkw', 'width': 2600}]",ChIJn5r_W5_z2YkR67VB2u5qyRw,2.0,4.3,ChIJn5r_W5_z2YkR67VB2u5qyRw,GOOGLE,"[cafe, bar, restaurant, food, point_of_interest, establishment]",...,43.041864,-76.136842,43.043212,-76.135400,43.040514,-76.138098,False,"2VR7+P7 Syracuse, NY, USA",87M52VR7+P7,NaN
4,CLOSED_TEMPORARILY,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Syracuse Suds Factory,"[{'height': 2666, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100850734738657404193"">Solas Studios Photography</a>'], 'photo_reference': 'ATtYBwJQxQ1udkNZkX6KsCVBZkAV-U3PXsnAtPx_m4mUy90kMaSjVa5Bm273lLBzB5IyEql31rDfd8D7be5aL5U1ohXCT2_JsKRj7PQ8mebI_bbwPa0fz-WoP7XWb67Fs-MwmQK83A5RgYc5sk3PGnw5LF6amb62MOG20cK1NQoysHCsDJVD', 'width': 4000}]",ChIJ42EzyLjz2YkRz4aKaDCeDbw,2.0,3.3,ChIJ42EzyLjz2YkRz4aKaDCeDbw,GOOGLE,"[bar, point_of_interest, establishment]",...,43.048113,-76.153888,43.049476,-76.152380,43.046778,-76.155078,NaN,"2RXW+6C Syracuse, NY, USA",87M52RXW+6C,True
5,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Saltine Warrior Sports Pub,"[{'height': 1000, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108754994177934343905"">Saltine Warrior Sports Pub</a>'], 'photo_reference': 'ATtYBwJFmS51jaikXggLhaCiNRVUarWeeIjjLATrGpXKEVBEQwX13-LqpfcsUl-4LQoqRiOnWxfvymrU05L1i-G9o-oXAIm3OoRXLFLvR-CXxGPTtIEbzxAnDqwYfHWG-PtoP1o1yUggxxuB2B1Hnj85OzTqa7x0bsjT0vrv_HO1RUZ8R31g', 'width': 1500}]",ChIJ4eXBZ7jz2YkRWwzq6jh85dM,2.0,4.0,ChIJ4eXBZ7jz2YkRWwzq6jh85dM,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.050740,-76.154507,43.052089,-76.153158,43.049391,-76.155856,True,"3R2W+75 Syracuse, NY, USA",87M53R2W+75,NaN
6,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Al's Wine & Whiskey Lounge,"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100361962513131275677"">Reine H</a>'], 'photo_reference': 'ATtYBwIj59e0ll3aS8lnqoA9Cp7PXAADE_28snh3toFrZE7DSkBPjlFNT_sth5G5EF4EoTvzhCLvHMOIMQn4BtXP-6cuEg_qZw0cRg2Vt5VMbOCYl32T3wShxK5S9dmnp2ZZnoH7YSm8wCC31nuIpBTo3bsCK39UdEwthx2t__N1FFrJGDM', 'width': 4032}]",ChIJVfyEyLjz2YkRf7FRJXkhgd0,2.0,4.6,ChIJVfyEyLjz2YkRf7FRJXkhgd0,GOOGLE,"[bar, point_of_interest, establishment]",...,43.048176,-76.153368,43.049546,-76.152121,43.046848,-76.154819,True,"2RXW+7M Syracuse, NY, USA",87M52RXW+7M,NaN
7,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Trexx,"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/114968416506485689423"">Theressa Bienvenue</a>'], 'photo_reference': 'ATtYBwJ_jqO8Tv6-oC9kVz5_bbNZt1oIpx1oBk3M4i9NGE9-FTI8p4WtAl0s4-6m0qkLgxAiwj3Xh98E0dMPOFQn1Iu-pebxg7-44z9Fz1M02leKJnunecOLxSc3pPuN2lBjZsjBRhkiHS6SXYZG1ITOYG3UD3wtLUnDXxbuXQWY6ITTx_IZ', 'width': 4032}]",ChIJnRi-jbfz2YkRBpeSSVhhMxE,1.0,4.1,ChIJnRi-jbfz2YkRBpeSSVhhMxE,GOOGLE,"[night_club, bar, restaurant, food, point_of_interest, establishment]",...,43.052942,-76.153755,43.054332,-76.152522,43.051634,-76.155220,False,"3R3W+5F Syracuse, NY, USA",87M53R3W+5F,NaN
8,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Guilfoil's Irish Pub,"[{'height': 452, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/101335463993932786042"">Guilfoil&#39;s Irish Pub</a>'], 'photo_reference': 'ATtYBwKtGwcfQ3tH_75DpxA0py90NKtPzm2SL3uYVv2wTk2LMMFVxg5qm9n2uRyqfGAFwUZ5iggJgrzXM2F7sVQkGSTdtSwOQBYC_PJggZr7iDKHs2p0pD-vqHzhzR8dxPfYlbsc2ibZoTsYVZ6AwkYBxdsYhh9cwgWrywOdEuS_Fj57eeSy', 'width': 804}]",ChIJDfWlPa_z2YkRHNJzLnjnILM,1.0,4.6,ChIJDfWlPa_z2YkRHNJzLnjnILM,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.052377,-76.138954,43.053638,-76.137607,43.050940,-76.140305,True,"3V26+XC Syracuse, NY, USA",87M53V26+XC,NaN
9,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,The Hops Spot,"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100236607195278254777"">Andrew Schutt</a>'], 'photo_reference': 'ATtYBwJtcEUCMz8fgp4W1eqbLDUs7tmIQY0GPIwUG6vOuiqMW89lmZLWTIXfo_wwF8kqjXE7vSDb60DmzXMvvHSvsalJIj0shuMnSV9frZZB9HYxCsSyPUTmUmTIqPv6vTwch1U5BcbxUHDsNIcQdjGFpttAhabGbTLwXjjztk5uMmndM4kJ', 'width': 4032}]",ChIJvfSLcA0T2IkRfWBTZpwlidY,2.0,4.4,ChIJvfSLcA0T2IkRfWBTZpwlidY,GOOGLE,"[bar, liquor_store, restaurant, food, point_of_interest, store, establishment]",...,43.048153,-76.154417,43.049409,-76.153082,43.046711,-76.155780,True,"2RXW+76 Syracuse, NY, USA",87M52RXW+76,NaN
10,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Maxwells,"[{'height': 1960, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108530648779026001981"">Maxwells</a>'], 'photo_reference': 'ATtYBwLALY9zCvPP70QAFnL28KPJ_uA3OCjzHPzV44RC-Fp_BBJMd6fmKERcOVlLA_UCzaNWHNT6iaAM0fi5ykO1iFMvH46Uh_8hKAhkjtVfxI0GCLwQJj4r08CvZb_5VUyMb1qYBpcEbgNXxruN2CJoT1HhMdbXiuZNvp9PIj4HKcJFzRYF', 'width': 1960}]",ChIJM86Fpbnz2YkRKrGFqtQqBi8,2.0,4.3,ChIJM86Fpbnz2YkRKrGFqtQqBi8,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.050120,-76.151505,43.051580,-76.150072,43.048882,-76.152770,True,"3R2X+29 Syracuse, NY, USA",87M53R2X+29,NaN
11,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Anything But Beer,"[{'height': 922, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/104981910177197126804"">Anything But Beer</a>'], 'photo_reference': 'ATtYBwIHd9ctpCeRKjeo8FP4z95lyYO3U7avwxS3Xr9htx87Jvy8ZBWs1EmLLFvvZ1sLl3TEuH9Yt43XPxBTVcCMJcLeCRibFqE6saXlXrQsOmYDtee1kjYxNoh-4DBjGOsB1pF8ADHZvVhzvep5SwhNZDiN9lRORPS27jDB-8Z0qmy98PYM', 'width': 918}]",ChIJgRICEd7z2YkREtShfi5Pgzo,NaN,4.5,ChIJgRICEd7z2YkREtShfi5Pgzo,GOOGLE,"[restaurant, meal_delivery, bar, food, point_of_interest, establishment]",...,43.049412,-76.152007,43.050773,-76.150762,43.048075,-76.153460,False,"2RXX+Q5 Syracuse, NY, USA",87M52RXX+Q5,NaN
12,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,The Evergreen,"[{'height': 1169, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/105467604264551483338"">The Evergreen</a>'], 'photo_reference': 'ATtYBwLMHL206ak_o6HUm1niDktCC1RDsjgRfbRKnju0rOywQZdT2KsiYmsplpWrsTxXpq9ZHkVndQNhb0BpId2IfOZ1cDRtTFED_vvP4Ptaj51-GErY8mRhtuZ5lI5CxkF1zeSKvHI9lOJI2bAon0hsqLV-APSL_bsiLkac_tlwYcRgoM5b', 'width': 1920}]",ChIJHegrubnz2YkRoEpk_R7BDTg,2.0,4.5,ChIJHegrubnz2YkRoEpk_R7BDTg,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.050697,-76.151272,43.052143,-76.149912,43.049445,-76.152610,True,"3R2X+7F Syracuse, NY, USA",87M53R2X+7F,NaN
13,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Weighlock Lounge,"[{'height': 1920, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/100030972936603522177"">Cat Lang</a>'], 'photo_reference': 'ATtYBwI2KNcNTUcrY1k4V0SjoblRrbguRHPAWzPOsRdR0tUiBnGBSGLsXU8CQuLxd8z7KQ5hO4FuS9DOE84-0Y23sNX4xNuE-bKVnnk1iXQ623kvT2_wuj5EYiaSh9ngHErMp62EPWLUWfXi5K2xSdDWsGd-9hQcqpNaKk21Rb4Msg2xtUk7', 'width': 1080}]",ChIJ2SNg6aTz2YkRa1B-BaUA2rA,NaN,4.8,ChIJ2SNg6aTz2YkRa1B-BaUA2rA,GOOGLE,"[bar, point_of_interest, establishment]",...,43.047661,-76.141877,43.049085,-76.140664,43.046387,-76.143362,False,"2VX5+36 Syracuse, NY, USA",87M52VX5+36,NaN
14,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Funk 'n Waffles,"[{'height': 381, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/113254511588149162028"">Funk &#39;n Waffles</a>'], 'photo_reference': 'ATtYBwLslllgY8-8yVQtqvOTKMLZJ7v1pHIQpS6ywYmA0WVgdQsh2LNwfihlN8r5yD1GB7C-8uPtKpyGTtSkiY_gEjjLIcjVDirLovYEIoDT5_s7Bqjhn2NZirSoLdQ1gbJ_3ErCva4negFgDfpBpfN0lGcS3c-T76tP0EEzeyz7UhfO_Ncn', 'width': 620}]",ChIJLX-Pxrjz2YkRLe-7F_VN3HE,NaN,4.4,ChIJLX-Pxrjz2YkRLe-7F_VN3HE,GOOGLE,"[cafe, bar, restaurant, food, point_of_interest, establishment]",...,43.048347,-76.153270,43.049704,-76.152074,43.047006,-76.154771,False,"2RXW+8M Syracuse, NY, USA",87M52RXW+8M,NaN
15,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Shaughnessy's Irish Pub,"[{'height': 4016, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/113943995077151847284"">Shaughnessy&#39;s Irish Pub</a>'], 'photo_reference': 'ATtYBwKbFXD6-eEWh1Sstd7qMGCGeE3ZZREzIqKqVn5g9aaOVR1XMSiG0xyST9d7-4jXJNVOWeAS39F-p8N6YE2TRpe33GIG0VyLDokkUKqx0YNth_rkc4luwZDcfbBdHtqwHM-oXRzH1MwfDX7itz9xSsmONUrVebXrNdTsWIOJRUMchIe6', 'width': 6016}]",ChIJo8R5WL7z2YkRRcysmcsM3yo,2.0,4.1,ChIJo8R5WL7z2YkRRcysmcsM3yo,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.044472,-76.151072,43.045751,-76.149781,43.043053,-76.152478,True,"2RVX+QH Syracuse, NY, USA",87M52RVX+QH,NaN
16,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,The York,"[{'height': 3024, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/106614825764704404196"">DeLancey Miller</a>'], 'photo_reference': 'ATtYBwJ5u7uXOKYxuVlbq3-2LocSA-HyzzPNg2vO-FXcWPfjyxbKvopVNmuzDNnz8h2POy0xC7QE1MpHKw4fz9fpOOEyfSEodVKAghTIUHxMbXMfbWSeXW4M9Q92ODoo-RN39W6ea3nvKaaP71TfD-Cc-Qbvjb44RKNicYlmnReN2-FruVzh', 'width': 3024}]",ChIJJdSLp7jz2YkRLDrtGu98O-M,2.0,4.3,ChIJJdSLp7jz2YkRLDrtGu98O-M,GOOGLE,"[night_club, bar, restaurant, food, point_of_interest, establishment]",...,43.048531,-76.155064,43.049970,-76.153714,43.047272,-76.156412,False,"2RXV+CX Syracuse, NY, USA",87M52RXV+CX,NaN
17,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Ale 'n' Angus Pub,"[{'height': 4032, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/102416727465053559547"">Ale &#39;n&#39; Angus Pub</a>'], 'photo_reference': 'ATtYBwK7iWaXqUYXGmwPfWNP8E1KbHbrxPi9aLg24L8mNzSWHs4pCLA-JaifAAcFqVuqKE6KMjv6iMrffh227sM6-azpaD9onwE8m3pJVPQduwmyC9Jo3BB4i5KB_xqEQnCVWhmIyKJ1D-oGJPJdV_0g4Npn8F82iOkEXU9BMgUQWgmVVOU', 'width': 3024}]",ChIJJa942r3z2YkREJnXnrSTZK0,2.0,4.5,ChIJJa942r3z2YkREJnXnrSTZK0,GOOGLE,"[bar, point_of_interest, establishment]",...,43.044218,-76.149062,43.045614,-76.147714,43.042916,-76.150412,False,"2VV2+M9 Syracuse, NY, USA",87M52VV2+M9,NaN
18,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png,Bistro Elephant,"[{'height': 1365, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/108937448623068417193"">Jim Hilker</a>'], 'photo_reference': 'ATtYBwLdwgSEj2Xwe1aTAHB_Muv22cogfOFKvhB8FzZgGGmPxoHkojedNrSHrlmt71KzdRJ92-0R0uVf4zar1w29uJnFzp5lyggr41IDldBSeMHjY3x-0rRrbuH_du5TGYpjtKIatllI580HeyVRWC84Tm6kMzLZIQuxVodHZgwHEkDVdo9p', 'width': 2048}]",ChIJL0sWVL_z2YkRQhZzBYHjmPs,NaN,4.4,ChIJL0sWVL_z2YkRQhZzBYHjmPs,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.047588,-76.154541,43.048854,-76.153143,43.046156,-76.155841,NaN,"2RXW+25 Syracuse, NY, USA",87M52RXW+25,NaN
19,OPERATIONAL,https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/bar-71.png,Clinton Street Pub,"[{'height': 4032, 'html_attributions': ['<a href=""https://maps.google.com/maps/contrib/107276703630995618848"">Clinton Street Pub</a>'], 'photo_reference': 'ATtYBwJ7XSmToaOHY0O9O1LAJM8tIBTBkO5sJLGQTHmz0ndmGSUv3tx4pgnUaYNpHgv0f_MEbhPo09rCBk-IaOgLhhaCAsl_DtPkKMsUSe7aT5JBUWwEcr_aGZsxnvNSawoCvm6LI9p39eX1eQWyacou6JOKx2BTZ_Tfon6fRFnj1Xi3Ciyg', 'width': 3024}]",ChIJvwKdwbjz2YkR2pHlLXgBxek,1.0,4.0,ChIJvwKdwbjz2YkR2pHlLXgBxek,GOOGLE,"[bar, restaurant, food, point_of_interest, establishment]",...,43.048529,-76.153391,43.049871,-76.152135,43.047173,-76.154833,True,"2RXW+CJ Syracuse, NY, USA",87M52RXW+CJ,NaN

## Challenge 5

Convert your dataframe back into a list of dict.

1. use `to_records()` to convert the dataframe in Challenge 4 back into a `list` of `dict`.
2. loop over the rows and print the bar name, rating, and whether it is open now, 
   for only those rows where the bar is open now.

NOTE: The keys match he columns in the data frame.

In [64]:
places_df.columns
for row in places_df.to_records():
    print(row['name'], row['rating'], row['opening_hours.open_now'])

Kitty Hoyne's Irish Pub 4.6 True
Phoebe's Restaurant & Coffee Lounge 4.6 False
Blue Tusk 4.4 True
Faegan's Cafe & Pub 4.3 False
Syracuse Suds Factory 3.3 nan
Saltine Warrior Sports Pub 4.0 True
Al's Wine & Whiskey Lounge 4.6 True
Trexx 4.1 False
Guilfoil's Irish Pub 4.6 True
The Hops Spot 4.4 True
Maxwells 4.3 True
Anything But Beer 4.5 False
The Evergreen 4.5 True
Weighlock Lounge 4.8 False
Funk 'n Waffles 4.4 False
Shaughnessy's Irish Pub 4.1 True
The York 4.3 False
Ale 'n' Angus Pub 4.5 False
Bistro Elephant 4.4 nan
Clinton Street Pub 4.0 True

In [68]:
bars_in_cuse = places_df.to_records()
print(f'These bars are open:')
for bar in bars_in_cuse:
    if bar['opening_hours.open_now'] == True:
        print(f"- {bar['name']}")

These bars are open:
- Kitty Hoyne's Irish Pub
- Blue Tusk
- Saltine Warrior Sports Pub
- Al's Wine & Whiskey Lounge
- Guilfoil's Irish Pub
- The Hops Spot
- Maxwells
- The Evergreen
- Shaughnessy's Irish Pub
- Clinton Street Pub

In [ ]:
# run this code to turn in your work!
from coursetools.submission import Submission
Submission().submit_now()